### ISSUE TITLE
Add Sprite Sheet PSD to Source Control

### ISSUE THREAD

**Issue by benbarnett** [moneyadviceservice/dough#201]
As the sprite sheet is a development asset, things are starting to get lost with half on Google Drive and half on here. Let's add the sprite sheet to this repo so we can manage it properly.

We could look at automatically generating this further down the line too.

**Comment by ourmaninamsterdam** [comment]
@benbarnett Now icons have been moved out of dough, could this be closed?

**Comment by benbarnett** [comment]
Yup :+1:
