### ISSUE TITLE
[WIP] TabSelector - tab items disappearing at smaller device widths

### ISSUE THREAD

**Issue by ourmaninamsterdam** [moneyadviceservice/dough#214]
**Wide viewports**
In wider views the tab items are displayed correctly.

![image](https://cloud.githubusercontent.com/assets/1579511/5756049/3c0fbbbe-9ca3-11e4-9b56-4a4ddbc030bb.png)

**Narrow viewports**
But in narrower viewports, the tab items disappear

https://www.moneyadviceservice.org.uk/en/tools/pension-calculator
* Firefox Latest 33.1
* Chrome Desktop  40.0.2214.94
* Chrome Android  40.0.2214.109
* Safari on iOS 8.1
* Safari on OSX  8.0.3 (10600.3.18)

Closed
![image](https://cloud.githubusercontent.com/assets/1579511/5756047/3350e5f2-9ca3-11e4-9638-8f3d11d0cb25.png)

Open
![image](https://cloud.githubusercontent.com/assets/1579511/5756077/b41fb9ec-9ca3-11e4-90a2-7d3b8dd7abf8.png)

Can be seen on https://www.moneyadviceservice.org.uk/en/styleguide/components/common and https://www.moneyadviceservice.org.uk/en/tools/pension-calculator

**Comment by ourmaninamsterdam** [comment]
It appears to be [this line](https://github.com/moneyadviceservice/dough/blob/ffd99a919870a48b029c1057417c9ac70831dab0/assets/stylesheets/components/optional/_tab_selector.scss#L93) causing the issue.

**Comment by Guntrisoft** [comment]
is this on a particular browser?

**Comment by Guntrisoft** [comment]
I can see it now on the stylesheet page, wondering what's different between that and the madewithdough site?

**Comment by ourmaninamsterdam** [comment]
Sorry, should have posted the browsers. Have updated the info above.

**Comment by Guntrisoft** [comment]
the madewithdough site has this line:

.tab-selector__trigger-container .tab-selector__trigger {
font-size: 1rem;
line-height: 1.5rem;
}

**Comment by ourmaninamsterdam** [comment]
Good spot. If you disable the `font-size: 1rem` on your snippet, then the `font-size: 0;` further up the tree on  `.tab-selector__triggers-inner` is inherited.

After digging a little further with @Guntrisoft, it's the removal of [this line](https://github.com/moneyadviceservice/dough/commit/27b95f5ed73633c3e800882c7ecc8e725ce29edd#diff-acfcb3f83b1a2decdd0ad334cc06d645L35) that triggered the issue.

We need to investigate what is the best course of action, whether to stick with my fix, or look at actually setting the font-size on the trigger, as `@extend %type` was doing previously. I shall investigate further.

**Comment by ourmaninamsterdam** [comment]
Fixed with afd2d133d102c35a63aab13062f24d4db660b581
