### ISSUE TITLE
Improve Javascript Documentation

### ISSUE THREAD

**Issue by benbarnett** [moneyadviceservice/dough#221]
Blog post?
Wiki?
Better comments in file?

We were talking about using jsDoc comments and then something like [dox](https://github.com/tj/dox) to generate them as HTML. That's also something that could be picked up on this.

**Comment by ourmaninamsterdam** [comment]
@benbarnett Better comments in the files would be my preference - with generation via dox. I'm happy to pick this up as a side project when I have downtime, as I need to do the same for the CMS.

**Comment by benbarnett** [comment]
That'd be great. I did a little spike on it in the early days using dox which may or may not be useful: https://github.com/moneyadviceservice/dough/blob/master/Gruntfile.js

**Comment by ourmaninamsterdam** [comment]
A decision was made to use _jsDoc_ for docs generation and _Gulp_ to facilitate the running of the task. 

https://github.com/moneyadviceservice/dough/pull/226 implements this.
